### ISSUE TITLE
Wins and losses

### ISSUE THREAD

**Issue by dagmarkramer** [rvan-duy/42-transcendence#88]

**Comment by dagmarkramer** [comment]
@rvan-mee kunnen we een getalletje voor wins en losses vanuit de backend aan deze endpoint toevoegen:  /user/id/1?withGames=true&withStatus=true ?

**Comment by dagmarkramer** [comment]
fixed

**Comment by rvan-duy** [comment]
I checked both on UserView and OtherUserView and wins/losses still seem to be hardcoded, is this correct @dagmarkramer ? If not you can close this issue, but for now I'm reopening it.

**Comment by dagmarkramer** [comment]
is fixed, was accidentally not merged with main
